ramdisk: If no internet connection found do not try to download which will cause freezes in Stweaks

diff --git a/ramdisk/res/customconfig/actions/boeffla_sound b/ramdisk/res/customconfig/actions/boeffla_sound
--- a/ramdisk/res/customconfig/actions/boeffla_sound
+++ b/ramdisk/res/customconfig/actions/boeffla_sound
@@ -1,13 +1,23 @@
 #!/sbin/busybox sh
 
-if [ ! -f /data/app/com.near.boefflasoun*.apk ]; then
-	# get boeflla sound from playstore
-	echo "You must download Boeffla Sound from Playstore in order to use these settings"
-	am start https://play.google.com/store/apps/details?id=com.near.boefflasound&hl=en > /dev/null 2>&1
-elif "$CONFIG_BOOTED" == "false" && [ -f /data/app/com.near.boefflasoun*.apk ]; then
-	# Killing Boeffla Sound if it was already open
-	echo "Starting Boeffla Sound App"
-	pkill -f "com.near.boefflasound" > /dev/null 2>&1
-	am start -a android.intent.action.MAIN -n com.near.boefflasound/com.near.boefflasound.activities.BoefflaSoundActivity > /dev/null 2>&1
+mount -o remount,rw /
+
+wget http://www.google.com -O ./temp > /dev/null 2>&1
+
+if [ $? -eq 0 ]; then
+	if [ ! -f /data/app/com.near.boefflasoun*.apk ]; then
+		# get boeflla sound from playstore
+		echo "You must download Boeffla Sound from Playstore in order to use these settings"
+		am start https://play.google.com/store/apps/details?id=com.near.boefflasound&hl=en > /dev/null 2>&1
+	elif "$CONFIG_BOOTED" == "false" && [ -f /data/app/com.near.boefflasoun*.apk ]; then
+		# Killing Boeffla Sound if it was already open
+		echo "Starting Boeffla Sound App"
+		pkill -f "com.near.boefflasound" > /dev/null 2>&1
+		am start -a android.intent.action.MAIN -n com.near.boefflasound/com.near.boefflasound.activities.BoefflaSoundActivity > /dev/null 2>&1
+	fi
+else
+	echo "Error: No Internet Connection Established"
 fi
 
+rm -f ./temp
+mount -o remount,ro /
